### ISSUE TITLE
feature: add a link to the REST OpenAPI docs in the navbar

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve-docs#2]
It should look similar to what's on the current docs: 

![image](https://github.com/devflowinc/trieve-docs/assets/15804464/0b4ef2aa-a5db-472a-bf1d-052443ed4d55)

**Comment by vid277** [comment]
Completed: 
<img width="960" alt="image" src="https://github.com/devflowinc/trieve-docs/assets/74870683/53f5b322-4ee7-478e-aef9-82be55605431">

**Comment by vid277** [comment]
<img width="959" alt="image" src="https://github.com/devflowinc/trieve-docs/assets/74870683/ffa8f818-95a5-471a-a72a-1633ece88b2b">
- Updated hover for REST OpenAPI button
